### ISSUE TITLE
Recursive bullet list in FunctionDoc

### ISSUE THREAD

**Issue by jakobrosenberg** [roxiness/routify.dev#140]
Currently the type and description are shown as sub-list items, which would imply properties in an object.

![image](https://user-images.githubusercontent.com/4153004/83500221-c4c1d400-a4be-11ea-88c4-581a23d9bfd6.png)

<details>
<summary>Example of nested bullets</summary>

![image](https://user-images.githubusercontent.com/4153004/83500751-7e20a980-a4bf-11ea-87c9-56a9fdae7355.png)
</details>

Type and description should be distinctive for an easier overview. Possibly with type data inlined with the property. @Wolfr, what do you think?

**Comment by Wolfr** [comment]
We could definitely improve this layout. I'll definitely take a look some time.
