### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify.dev#142]
We discussed having search functionality in the Routify docs on Discord.

I proposed a simple solution with just filtering the strings in the sidebar to begin with.

Other people can probably do a smarter implementation but this is what I know. A bit like how the search works here: http://bs4base.bedrockapp.org/styleguide/docs/introduction.html

WIP code for this: https://svelte.dev/repl/0a60b54d5df64a23bc53207838639898?version=3.23.0

I would welcome somebody who could improve this filter code.

---

A 2nd idea would be to embed keywords into an object and then use those to filter on as well.

See this REPL: https://svelte.dev/repl/4daa1f7a036c488593038127a1145b25?version=3.23.0

**Comment by jakobrosenberg** [comment]
Till we get fulltext search, we can make do with adding keywords in metadata/frontmatter.

```javascript
const matchingPosts = blogPostNodes.filter(node => node.meta.frontmatter.keywords.includes(searchString))
```
```html
{#each matchingPosts as post}
  <a href={post.path}>{post.title}</a>
{/each}
