### ISSUE TITLE
Metadata Docs Issues

### ISSUE THREAD

**Issue by parker-codes** [roxiness/routify.dev#150]
Hey, I read through the Metadata page and ran into some issues. First of all, great framework!

---

> To add metadata, insert a comment with routify:options

My issue was that I tried to do a multi-line comment to have multiple options, but it didn't work. So this could probably say "insert a single-line comment".

> The metadata can then be accessed through $route.meta
> 
> ```js
> import { route } from @sveltech/routify
> const { meta } = $route
> ```

While this part was definitely true, it is not reactive. Switching pages does not update the meta values because `meta` has been destructured/detached from the `$route` store. So I did this:

```js
let pageTitle: string;
$: pageTitle = ($route as any).meta.pageTitle || '';
```

A last thing to note is that I had to do `($route as any)` because the return type of the store is `never`. So that is a bug as well and won't let my code compile without this override.

**Comment by ghostdevv** [comment]
Feel free to reopen this if it's still an issue but I believe it's not @parker-codes
