### ISSUE TITLE
Clarify routify:options can take only one value, or allow multiple

### ISSUE THREAD

**Issue by tv42** [roxiness/routify.dev#179]
https://routify.dev/docs/metadata

This doesn't seem to work:

```
<!-- routify:options title="Foo" index=1 -->
```

This does:

```
<!-- routify:options title="Foo" -->
<!-- routify:options index=1 -->
```

That difference is not really documented. Either document, or allow multiple options.

If not allowing multiple options, `<!-- routify:options title="Foo" index=1 -->` should cause an error.

**Comment by Wolfr** [comment]
We should change this in the docs. Noted.
