### ISSUE TITLE
Guide starts with a metadata link, which links to the docs section

### ISSUE THREAD

**Issue by Wolfr** [roxiness/routify.dev#180]
![image](https://user-images.githubusercontent.com/12690/91410189-d4934f00-e846-11ea-914c-bd867a1aa1ac.png)

Seems like this metadata link, which then links out to https://routify.dev/docs/metatags is placed wrongly.

**Comment by josefaidt** [comment]
Hi @Wolfr I'll take this on as well! This page currently appears to be empty, should it be removed? If not, what content should be populated and where do you feel it is more appropriate to place in the side navigation?
