### ISSUE TITLE
basepath: Docs never explain what it actually is

### ISSUE THREAD

**Issue by tv42** [roxiness/routify.dev#190]
> Basepaths can be set by importing the basepath helper. Basepaths must be strings but will be converted to a RegExp.

> Using basepaths with subfolders

etc. Nothing says what a basepath is, and why you might want to set it.

This needs an intro like (guessing at the right answers)

Basepath is a prefix of the URL path that is ignored for routing decisions. For example, setting `$basepath = "/foo"`, a request for `/foo/bar` would be routed as if it was a request for `/bar`.

**Comment by Wolfr** [comment]
Good doc addition suggestion. Will leave this open until we have this extra info on the site. 

@jakobrosenberg do you agree with the explanation?

**Comment by jakobrosenberg** [comment]
Why isn't Github notifying me of these issues? 🤔 I only got a notification about @Wolfr replying to it.

Anyway. Basepath was deprecated in favor of **urlTranform** in Routify 2, so the primary focus will be on documenting `urlTransform`, which may get its own basepath helper down the road.
