### ISSUE TITLE
`routify export` seems completely undocumented?

### ISSUE THREAD

**Issue by tv42** [roxiness/routify.dev#191]
I couldn't find anything actually explaining what `routify export` does. I changed my rollup destination directory, but it seems that `routify export` expects a specific layout for the files: you can set the name of the `dist` directory, but `DIST_NAME_HERE/build/bundle.js` and `DIST_NAME_HERE/__app.html` must exist.

**Comment by Wolfr** [comment]
It is part of the build process to generate static pages (SSR versions). 

Related code:
https://github.com/roxiness/routify/blob/master/lib/services/exporter.js

**Comment by jakobrosenberg** [comment]
The exporter is dead. All hail the exporter.

https://github.com/roxiness/spank

Once Spank  has been added to the starter template, it will become the de-facto exporter. 

Considering that Routify 2 is still tagged as `next-major`, would it be reasonable to remove the old exporter function before releasing it as stable?
