### ISSUE TITLE
'Get Started' button on home page throws and error

### ISSUE THREAD

**Issue by benwoodward** [roxiness/routify.dev#195]
`Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec. _layout-edc22379.js:1`

`getting-started:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://routify.dev/build/_layout-edc22379.js`

![image](https://user-images.githubusercontent.com/1472981/96389285-30f16a00-120b-11eb-909f-828961b11bed.png)

**Comment by peopledrivemecrazy** [comment]
Strange, this doesn't happen to me. Maybe the layout chunk isn't fully downloaded.

**Comment by benwoodward** [comment]
I just tested again and it works.. but not in an incognito window... and then after a few seconds (in the incognito) I try clicking again and it then works.

**Comment by peopledrivemecrazy** [comment]
Somehow I am not able to reproduce this error. Tested on Edge (Chromium) and Chrome.

**Comment by Wolfr** [comment]
Visiting the Routify site, the first time I clicked on getting started it did not do anything, second time I got the page to load. Maybe some old cache thing conflicting with something new...

**Comment by ghostdevv** [comment]
This doesn't seem to be an issue still
