### ISSUE TITLE
Website performance

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [roxiness/routify.dev#208]
I just ran a lighthouse test over the site that can be found [here](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Froutify.dev). I think we can improve things like using prefetch to get a better result.

**Comment by jakobrosenberg** [comment]
I think Lighthouse has the wrong impression of workbox. Can we tell it that workbox is not a key request?

**Comment by HAUDRAUFHAUN** [comment]
> I think Lighthouse has the wrong impression of workbox. Can we tell it that workbox is not a key request?

I'll research

**Comment by ghostdevv** [comment]
Any updates on this @HAUDRAUFHAUN

**Comment by HAUDRAUFHAUN** [comment]
I just took a deeper look on that workbox think, it isn't affecting that [much](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Froutify.dev#performance). It's only suggesting that the request should be preloaded. I'm not that much expierenced with this kind of setup, but maybe you now where to add it...

**Comment by jakobrosenberg** [comment]
Workbox handles the serviceworker which is a low priority request. Google Lighthouse doesn't know it's a low priority request and I'm not sure we can tell it.

I'm closing this for now.
