### ISSUE TITLE
Spelling error: SSR & SSG documentation section

### ISSUE THREAD

**Issue by wolfbyne** [roxiness/routify.dev#215]
The documentation says:

### Disabling
While SPA, PWA, SSR, SSG, Dynamic imports etc. all happily coexist, there can be times where you want to disable _**on**_ or more features.

but the "on" should be "one" so to read as follows:

### Disabling
While SPA, PWA, SSR, SSG, Dynamic imports etc. all happily coexist, there can be times where you want to disable _**one**_ or more features.

**Comment by jakobrosenberg** [comment]
Thanks @wolfbyne. Interest in doing a PR? 🙂

**Comment by wolfbyne** [comment]
Will do.
