### ISSUE TITLE
Migrating to 2.x guide missing information on Routify rollup plugin is now an object

### ISSUE THREAD

**Issue by hobbitronics** [roxiness/routify.dev#217]
While recently migrating from @sveltech/routify to @roxi/routify I was getting the following error: `[!] TypeError: rollup.routify is not a function` from my rollup.config.js file.

While the migration guide does say, "The Routify rollup plugin, now has to be imported from @roxi/routify/plugins/rollup," it does not mention that `import { routify } from '@roxi/routify/plugins/rollup'` will no longer work, but
`import routify from '@roxi/routify/plugins/rollup'`
must be used.

**Comment by jakobrosenberg** [comment]
Thanks @hobbitronics . I've updated the page.
