### ISSUE TITLE
Migrating to 2.x guide missing information on Routify rollup.config.js changes.

### ISSUE THREAD

**Issue by hobbitronics** [roxiness/routify.dev#218]
While migrating to 2.x I also found it necessary to add the options below to my rollup.config.js file to avoid the following:
`(!) To preserve the export signature of the entry module "src/main.js", an empty facade chunk was created...`and
`Error: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.`

solution:

`preserveEntrySignatures: 'strict',
	inlineDynamicImports: true,`

**Comment by jakobrosenberg** [comment]
Does this also fix the issue?
```json
//package.json
"routify": {
  "dynamicImports": false
}

**Comment by hobbitronics** [comment]
Yeah, that does the trick too.

**Comment by jakobrosenberg** [comment]
Thanks. Updated the docs.
