### ISSUE TITLE
routify.dev loop switching between 1.x and 2.x

### ISSUE THREAD

**Issue by ksuedile** [roxiness/routify.dev#222]
Use case,
use an adblock (mine is uBlock Origin), and go visit https://routify.dev/guide/installation

Your browser is looping in redirection between v1.x and v2.x of routify.
The cause seems to be plausible.io. Indeed, in network tab of chrome tools, we can see it's a blocked request, blocked by the adblocker.

Please manage this case. Routify is a good product, such a lame bug on the guide pages should not happen just because we use an adblocker

**Comment by ksuedile** [comment]
i just upgrade my chrome browser. The bug is not reproduced anymore.
I close the ticket. Thank you for having tested it. Sorry for the time lost

**Comment by jakobrosenberg** [comment]
No problem. Better safe than sorry. 🙂
